### PR TITLE
Add ability to configure the transaction timeout

### PR DESCRIPTION
**Pull request by morelazers**

### CODE REVIEW

**Comment by leewillis77** [comment]
Hi Tom; 

Why would someone want (or need) to do this? Can't we just set a sensible value and do away with the setting.

WooCommerce will hold orders for 60 minutes by default, so maybe set this to 50 for all orders, do away with the UI, and just leave a filter so people can change it with a snippt if they *really* need to?

**Comment by morelazers** [comment]
@leewillis77 Didn't know about the WooCommerce default of 60 minutes.

A couple of API customers have mentioned that they would prefer if their store's customers had more time to pay (some of them might not have ETH in the right place, or need to fetch a wallet or something similar), and that the 20 minute default wasn't enough.

Agree that a sensible default & hook is a better solution - I'm unsure how to implement the hook though, could you point me to the right place for docs and I'll update the PR when I get a chance?

**Comment by leewillis77** [comment]
Hi; 

I've added it in here: https://github.com/leewillis77/pay-with-ether/commit/49cce35bed6b067e8340da5a25fd24ce59c84a39#diff-132a36fbd7edbd70d3c5b1a7f2b28eb8R344

Filters are implemented with `apply_filters()` - so you give it a unique name (`pwe_transaction_timeout` in this example), pass the default value as the second parameter, and any other useful information that people might need as subsequent parameters. Here we're passing the order ID in case someone wants to implement different timeouts for different orders. 

Someone could override this by adding a snippet like this:

```php
add_filter( 'pwe_transaction_timeout', function ( $timeout, $order_id ) {
    // Set the timeout to 1hr (3600 seconds)
    return 3600;
}, 10, 2 );
```

Let me know when the API end supports this and I'll get a release pushed out.

**Comment by morelazers** [comment]
API supports the change - let's go :-)

**Comment by leewillis77** [comment]
v1.3.1 on its way up to WordPress.org right now ...

**Pull request closed without merging**
